//
//  Assemblies.swift
//  CoordinatorHelper
//
//  Created by Mike Kholomeev on 12/14/17.
//  Copyright © 2017 Mike Kholomeev. All rights reserved.
//

import Foundation
import Files

class Assemblies {
    let coordinatorAssemblyFile:File
    let screenAssemblyFile:File

    init(coordinatorAssemblyFile:File, screenAssemblyFile:File) {
        self.coordinatorAssemblyFile = coordinatorAssemblyFile
        self.screenAssemblyFile = screenAssemblyFile
    }

    // MARK: - Public
    func addCoordinatorScreenCreation(named:String) throws {
        let insertedCoordinatorText = coordinatorCreationText(named)
        let insertedScreenText = vcCreationText(named)

        try TextFunc.insert(insertedCoordinatorText, into: coordinatorAssemblyFile)
        try TextFunc.insert(insertedScreenText, into: screenAssemblyFile)
    }
    
    // MARK: - Private
    fileprivate func coordinatorCreationText(_ named:String) -> String {
        let smallName = named.lowercasingFirstLetter()
        let bigName = named.capitalizingFirstLetter()
        
        let importText = """
        //MARK - AUTOGENERATED via CoordinatorHelper
        //MARK - \(bigName)Coordinator
            lazy var \(smallName)Coordinator: \(bigName)Coordinator = {
        let coordinator = \(bigName)Coordinator(router, assembly:self, screenAssembly:screenAssembly) //,sourceView:mainCoordinator.sourceView) {
                return coordinator
            }()
        //MARK - AUTOGENERATED via CoordinatorHelper END

        """
        
        return importText
    }
    
    fileprivate func vcCreationText(_ named:String) -> String {
        let smallName = named.lowercasingFirstLetter()
        let bigName = named.capitalizingFirstLetter()
        
        let importText = """
        //MARK - AUTOGENERATED via CoordinatorHelper
        //MARK - \(bigName)Screen
            lazy var \(smallName)Screen: \(bigName)Screen = {
                let vc = \(bigName)Screen.instantiateFromStoryboard()
                vc.delegate = delegate
            return vc
            }()
        //MARK - AUTOGENERATED via CoordinatorHelper END
        
        """
        
        return importText
    }
}
